

import Layout from "@/component/Layout";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#f1f1f1] w-full min-h-screen p-4'>
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
